backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

site_url: "https://tanyaradzwa-mapuwei.co.za"
display_url: "https://tanyaradzwa-mapuwei.co.za"
logo_url: "/assets/images/favicon.png"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }

      - { label: "Date", name: "date", widget: "datetime" }

      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - "Tech Compass"
          - "Music & Moments"
          - "Tanya’s Table"
          - "My Faith"
          - "Out & About"
          - "Rooted Living"

      - { label: "Featured Image", name: "image", widget: "image", required: false }

      - { label: "Short Description", name: "description", widget: "text" }

      - { label: "Tags", name: "tags", widget: "hidden", default: "post" }

      - { label: "Body", name: "body", widget: "markdown" }

  - name: "diaries"
    label: "Diary Entries"
    folder: "src/content/diaries"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Tags", name: "tags", widget: "hidden", default: "diary" }

      - { label: "Permalink", name: "permalink", widget: "hidden", default: false }

      - label: "Diary"
        name: "diary"
        widget: "select"
        options:
          - "Web Development"
          - "Java"
          - "C#"
          - "PHP"
          - "Business Analyst"
          - "Test Analyst"

      - { label: "Name of Project", name: "projectName", widget: "string" }

      - { label: "Overseer", name: "overseer", widget: "string", required: false }

      - { label: "Link to Project", name: "projectLink", widget: "string", required: false }

      - label: "Status"
        name: "status"
        widget: "select"
        options:
          - "Planning"
          - "In Progress"
          - "Completed"
          - "Paused"

      - { label: "Tools Used", name: "toolsUsed", widget: "string", required: false }

      - { label: "Notes", name: "notes", widget: "text", required: false }